name: DEPLOY
on:
    push:
        branches: [main]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: prod-cluster-1    # Add your cluster name here.
  GKE_ZONE: europe-west1   # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.
  IMAGE: static-site

jobs:
    build:
        runs-on: [self-hosted, gke]
        steps:
            - run: echo "test ok"

            - name: Checkout
              uses: actions/checkout@v3

            - name: Set gcloud CLI
              run: gcloud auth activate-service-account --key-file=/home/camegan/key.json

            - name: Set get cluster
              run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_ZONE }} --project ${{ env.PROJECT_ID }}
